FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1
ENV PATH=/usr/local/bin:$PATH
WORKDIR /app

RUN apt-get update && apt-get install -y gcc libpq-dev

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
 
RUN python manage.py collectstatic --noinput
RUN chmod +x /app/start.sh


CMD ["./start.sh"]